#pragma once

#define STATUS_ERR_SOLAR_TRACER_NO_SYNC_ST 1
#define STATUS_ERR_SOLAR_TRACER_NO_SYNC_RT 2
#define STATUS_ERR_SOLAR_TRACER_NO_SYNC 3
#define STATUS_ERR_NO_CONNECTION 4
#define STATUS_RUN_BOOTING 8
#define STATUS_ERR_SOLAR_TRACER_NO_COMMUNICATION 16

