#include "../epever/epever_config.h"

#if (SOLAR_TRACER_MODEL == EPEVER_SOLAR_TRACER_A | SOLAR_TRACER_MODEL == EPEVER_SOLAR_TRACER_B | SOLAR_TRACER_MODEL == EPEVER_SOLAR_TRACER_TRITON | SOLAR_TRACER_MODEL == EPEVER_SOLAR_TRACER_XTRA)
#include "../epever/EPEVERSolarTracer.h"
#ifdef USE_SERIAL_MAX485
#define SOLAR_TRACER_INSTANCE EPEVERSolarTracer(BOARD_ST_SERIAL_STREAM, SERIAL_COMMUNICATION_TIMEOUT, MODBUS_SLAVE_ID, MAX485_DE, MAX485_RE_NEG)
#else
#define SOLAR_TRACER_INSTANCE EPEVERSolarTracer(BOARD_ST_SERIAL_STREAM, SERIAL_COMMUNICATION_TIMEOUT, MODBUS_SLAVE_ID)
#endif
#elif (SOLAR_TRACER_MODEL == DUMMY_SOLAR_TRACER)
#include "../dummy/DummySolarTracer.h"
#define SOLAR_TRACER_INSTANCE DummySolarTracer()
#endif