#ifndef BOARD_DEBUG_SERIAL_STREAM
#define BOARD_DEBUG_SERIAL_STREAM Serial
#endif

#ifndef BOARD_DEBUG_SERIAL_STREAM_BAUDRATE
#define BOARD_DEBUG_SERIAL_STREAM_BAUDRATE 115200
#endif

#if defined(USE_SERIAL_STREAM) & !defined(BOARD_SERIAL_STREAM)
#define BOARD_SERIAL_STREAM Serial
#endif


#if defined(USE_SERIAL_MAX485) & !defined(MAX485_DE)
#define MAX485_DE D1
#endif

#if defined(USE_SERIAL_MAX485) & !defined(MAX485_RE_NEG)
#define MAX485_RE_NEG D1
#endif
