#define CONFIG_PERSISTENCE "/config.json"



#define CONFIG_PERSISTENCE_WIFI_SSID "ssid"
#define CONFIG_PERSISTENCE_WIFI_SSID_LEN 20

#define CONFIG_PERSISTENCE_WIFI_PASSWORD "passw"
#define CONFIG_PERSISTENCE_WIFI_PASSWORD_LEN 30

#define CONFIG_PERSISTENCE_WIFI_BLYNK_AUTH "blynkToken"
#define CONFIG_PERSISTENCE_WIFI_BLYNK_AUTH_LEN 32

#define CONFIG_PERSISTENCE_WIFI_BLYNK_IS_LOCAL "blynkLocal"

#define CONFIG_PERSISTENCE_WIFI_BLYNK_HOSTNAME "blynkHostname"
#define CONFIG_PERSISTENCE_WIFI_BLYNK_HOSTNAME_LEN 20

#define CONFIG_PERSISTENCE_WIFI_BLYNK_PORT "blynkPort"

