/**
 * Solar Tracer Blynk V3 [https://github.com/Bettapro/Solar-Tracer-Blynk-V3]
 * Copyright (c) 2021 Alberto Bettin
 *
 * Based on the work of @jaminNZx and @tekk.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

#ifndef EPEVER_modbus_address_h
#define EPEVER_modbus_address_h

#define MODBUS_ADDRESS_PV_VOLTAGE 0x3100
#define MODBUS_ADDRESS_PV_POWER 0x3102
#define MODBUS_ADDRESS_PV_CURRENT 0x3101
#define MODBUS_ADDRESS_LOAD_CURRENT 0x310D
#define MODBUS_ADDRESS_LOAD_POWER 0x310E
#define MODBUS_ADDRESS_BATT_TEMP 0x3110
#define MODBUS_ADDRESS_BATT_VOLTAGE 0x3104
#define MODBUS_ADDRESS_BATT_SOC 0x311A
#define MODBUS_ADDRESS_BATTERY_CHARGE_CURRENT 0x3105
#define MODBUS_ADDRESS_BATTERY_CHARGE_POWER 0x3106
#define MODBUS_ADDRESS_BATTERY_OVERALL_CURRENT 0x331B
#define MODBUS_ADDRESS_LOAD_FORCE_ONOFF 0x0006
#define MODBUS_ADDRESS_LOAD_MANUAL_ONOFF 0x0002
#define MODBUS_ADDRESS_BATTERY_CHARGE_ONOFF 0x0000
#define MODBUS_ADDRESS_BATTERY_STATUS 0x3200
#define MODBUS_ADDRESS_CHARGING_EQUIPMENT_STATUS 0x3200
#define MODBUS_ADDRESS_DISCHARGING_EQUIPMENT_STATUS 0x3200
#define MODBUS_ADDRESS_STAT_MAX_PV_VOLTAGE_TODAY 0x3300
#define MODBUS_ADDRESS_STAT_GENERATED_ENERGY_TODAY 0x330C
#define MODBUS_ADDRESS_STAT_GENERATED_ENERGY_MONTH 0x330E
#define MODBUS_ADDRESS_STAT_GENERATED_ENERGY_YEAR 0x3310
#define MODBUS_ADDRESS_CONTROLLER_TEMP 0x3111
#define MODBUS_ADDRESS_REMOTE_BATTERY_TEMP 0x311B
#define MODBUS_ADDRESS_REALTIME_CLOCK 0x9013
#define MODBUS_ADDRESS_BATTERY_TYPE 0x9000
#define MODBUS_ADDRESS_BATTERY_CAPACITY 0x9001
#define MODBUS_ADDRESS_BATTERY_TEMP_COEFF 0x9002
#define MODBUS_ADDRESS_HIGH_VOLTAGE_DISCONNECT 0x9003
#define MODBUS_ADDRESS_CHARGING_LIMIT_VOLTAGE 0x9004
#define MODBUS_ADDRESS_OVER_VOLTAGE_RECONNECT 0x9005
#define MODBUS_ADDRESS_EQUALIZATION_VOLTAGE 0x9006
#define MODBUS_ADDRESS_BOOST_VOLTAGE 0x9007
#define MODBUS_ADDRESS_FLOAT_VOLTAGE 0x9008
#define MODBUS_ADDRESS_BOOST_RECONNECT_VOLTAGE 0x9009
#define MODBUS_ADDRESS_LOW_VOLTAGE_RECONNECT 0x900A
#define MODBUS_ADDRESS_UNDER_VOLTAGE_RECOVER 0x900B
#define MODBUS_ADDRESS_UNDER_VOLTAGE_WARNING 0x900C
#define MODBUS_ADDRESS_LOW_VOLTAGE_DISCONNECT 0x900D
#define MODBUS_ADDRESS_DISCHARGING_LIMIT_VOLTAGE 0x900E
#define MODBUS_ADDRESS_BATTERY_RATED_LEVEL 0x9067
#define MODBUS_ADDRESS_EQUALIZE_DURATION 0x906B
#define MODBUS_ADDRESS_BOOST_DURATION 0x906C
#define MODBUS_ADDRESS_CHARGING_MODE 0x9070

#endif